# Generated by Django 4.1.1 on 2022-10-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='group_scientific_name',
            new_name='scientific_name',
        ),
    ]
