# Generated by Django 4.1.1 on 2022-10-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_rename_scientific_name_animal_group_alter_animal_sex'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='animals',
            field=models.ManyToManyField(related_name='trait', to='animals.animal'),
        ),
    ]
