# Generated by Django 4.1.1 on 2022-10-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_alter_trait_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='animals',
        ),
    ]
